#Dockerfile, Image, Container
FROM python:3.8.2

# RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
#     apt-get install -y -q --no-install-recommends python3-opencv && \
#     rm -rf /var/lib/apt/lists/*

RUN pip install numpy opencv-python-headless requests
RUN echo 'Ja pots iniciar el client'
#CMD ["python", "./client_example.py", "rebe.jpeg"]

ADD client_example.py .