#Dockerfile, Image, Container

#FROM ubuntu:focal

FROM python:3.7-slim as build

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y -q --no-install-recommends protobuf-compiler libgl1-mesa-dev libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip grpcio-tools protobuf numpy opencv-python-headless pandas pillow imutils flask flask_restful response
#RUN git clone https://github.com/HiEST/cova-tuner.git
#RUN cd cova-tuner 
ADD /cova-tuner /cova-tuner
WORKDIR "/cova-tuner"
RUN pip install -e .

FROM python:3.7-slim
COPY --from=build /usr/local/lib/python3.7/site-packages /usr/local/lib/python3.7/site-packages
RUN apt-get update
#RUN apt install -y ffmpeg libsm6 libxext6 
RUN apt install libgl1-mesa-glx libsm6 ffmpeg -y

COPY /models /models
COPY /cova-tuner /cova-tuner
#ENV DEBIAN_FRONTEND=noninteractive

ADD server.py .

ENTRYPOINT ["python", "./server.py"]