#Dockerfile, Image, Container

#FROM ubuntu:focal

FROM python:3.7-slim as build


RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y -q --no-install-recommends protobuf-compiler libgl1-mesa-dev libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*
    #sudo apt-get install -y 

RUN pip install --upgrade pip grpcio-tools protobuf numpy opencv-python-headless pandas pillow imutils flask flask_restful response
#RUN git clone https://github.com/HiEST/cova-tuner.git
#RUN cd cova-tuner 
ADD /cova-tuner /cova-tuner
WORKDIR "/cova-tuner"
RUN pip install -e .

FROM python:3.7-slim
COPY --from=build /usr/local/lib/python3.7/site-packages /usr/local/lib/python3.7/site-packages


#RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    #apt-get install -y -q --no-install-recommends libgl1-mesa-dev libglib2.0-0 && \
    #rm -rf /var/lib/apt/lists/* && \
    

#ENV DEBIAN_FRONTEND=noninteractive
#RUN apt-get update

#RUN apt-get install -y python3.8\
#    python3-pip
#RUN rm -rf /var/lib/apt/lists/*
#pip install numpy\
#    opencv-python-headless\
#    pandas\
#    flask\
#    flask_restful\
#    response\
#    openvino-python

ADD server_example_oV.py .

ENTRYPOINT ["python", "./server_example_oV.py"]

# RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
#     apt-get install -y -q --no-install-recommends python3-opencv && \
#     rm -rf /var/lib/apt/lists/*


